package interfaces;

import classes.Department;
import classes.MyConnection;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class DepartmentManage extends javax.swing.JFrame {
    
    private String userN;
    private String userT;

    public DepartmentManage(String userName, String userType) {
        initComponents();
        showAll();
        
        //Save user Details
        userN = userName;
        userT = userType;
        
        
                //Login Image fit to screen
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("3d-casual-life-searching-for-new-employees.png")));
        
        Image img1 = myimage.getImage();
        Image img2 = img1.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        jLabel3.setIcon(i);
        
        addTableSelectionListener();
    }
    
    public DepartmentManage(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDepartmentID = new javax.swing.JLabel();
        txtDepID = new javax.swing.JTextField();
        txtDepName = new javax.swing.JTextField();
        lblDepName = new javax.swing.JLabel();
        txtDepSearch = new javax.swing.JTextField();
        btnDepSearch = new javax.swing.JButton();
        btnDepAdd = new javax.swing.JButton();
        btnDepUpdate = new javax.swing.JButton();
        btnDepLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDepartment = new javax.swing.JTable();
        btnDepDelete = new javax.swing.JButton();
        btnDepRefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDepartmentID.setText("DEPARTMENT ID");
        jPanel1.add(lblDepartmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));
        jPanel1.add(txtDepID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 320, 32));
        jPanel1.add(txtDepName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 320, 32));

        lblDepName.setText("DEPARTMENT NAME");
        jPanel1.add(lblDepName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));
        jPanel1.add(txtDepSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 260, 39));

        btnDepSearch.setText("SEARCH");
        btnDepSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnDepSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 120, 33));

        btnDepAdd.setText("ADD");
        btnDepAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnDepAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 99, 33));

        btnDepUpdate.setText("UPDATE");
        btnDepUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnDepUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 99, 33));

        btnDepLogout.setText("BACK");
        btnDepLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnDepLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, 110, 33));

        tblDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "DEPARTMENT ID", "DEPARTMENT NAME"
            }
        ));
        jScrollPane1.setViewportView(tblDepartment);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 320));

        btnDepDelete.setText("DELETE");
        btnDepDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDepDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 99, 33));

        btnDepRefresh.setText("REFRESH");
        btnDepRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnDepRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 99, 33));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 370, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepSearchActionPerformed
        Department search = new Department();
        search.setDepID(txtDepSearch.getText());
        search.setDepName(txtDepSearch.getText());
        
        if(search.searchDepartment()){
            JOptionPane.showMessageDialog(null, "DEPARTMENT FOUND!","SEARCHING...",JOptionPane.INFORMATION_MESSAGE);
            txtDepID.setText(search.getDepID());
            txtDepName.setText(search.getDepName());
            
            DefaultTableModel model = (DefaultTableModel)tblDepartment.getModel();
            model.setRowCount(0);
            
            model.addRow(new String[]{search.getDepID(),search.getDepName()});
        }else{
            
            JOptionPane.showMessageDialog(null, "DEPARTMENT NOT FOUND!","NOT FOUND",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btnDepSearchActionPerformed

    private void btnDepAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepAddActionPerformed
        Department add = new Department();
        add.setDepID(txtDepID.getText());
        add.setDepName(txtDepName.getText());
        
        if(add.addDepartment()){
            JOptionPane.showMessageDialog(null, "NEW DEPARTMENT ADDED!","NEW DEPARTMENT",JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            JOptionPane.showMessageDialog(null, "DEPARTMENT NOT INSERTED, TRY AGAIN!","ERROR",JOptionPane.ERROR_MESSAGE);
            
        }
        
        clear();
        showAll();
        
    }//GEN-LAST:event_btnDepAddActionPerformed

    private void btnDepDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepDeleteActionPerformed
        Department delete = new Department();
        delete.setDepID(txtDepID.getText());
        
        if(delete.deleteDepartment()){
            JOptionPane.showMessageDialog(null, "DEPARTMENT DELETED!","DELETE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "DEPARTMENT NOT DELETED, TRY AGAIN!","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        clear();
        showAll();
    }//GEN-LAST:event_btnDepDeleteActionPerformed

    private void btnDepUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepUpdateActionPerformed
        Department update = new Department();
        update.setDepID(txtDepID.getText());
        update.setDepName(txtDepName.getText());
        
        if(update.updateDepartment()){
            JOptionPane.showMessageDialog(null, "DEPARTMENT UPDATED!","UPDATED!",JOptionPane.INFORMATION_MESSAGE);
           
        }else{
            
            JOptionPane.showMessageDialog(null, "DEPARTMENT NOT UPDATED!","ERROR!",JOptionPane.ERROR_MESSAGE);
            
            
        }
        
        showAll();
                
    }//GEN-LAST:event_btnDepUpdateActionPerformed

    private void btnDepLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepLogoutActionPerformed
        EmployeeManage logout = new EmployeeManage(userN,userT);
        logout.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDepLogoutActionPerformed

    private void btnDepRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepRefreshActionPerformed
        showAll();
    }//GEN-LAST:event_btnDepRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentManage().setVisible(true);
            }
        });
    }
    
    public void addTableSelectionListener(){
       tblDepartment.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
           @Override
           public void valueChanged(ListSelectionEvent e) {
               if(!e.getValueIsAdjusting()){
                   int selectedRow = tblDepartment.getSelectedRow();
                   
                   if(selectedRow != -1){
                       txtDepID.setText(tblDepartment.getValueAt(selectedRow,0).toString());
                       txtDepName.setText(tblDepartment.getValueAt(selectedRow, 1).toString());
                   }
               }
           }
       });
    }
    
    
    
    private void showAll(){
        
        DefaultTableModel table = (DefaultTableModel)tblDepartment.getModel();
        table.setRowCount(0);
        
        Department show = new Department();
        show.viewAll();
        
        try {
            
            MyConnection.rs = MyConnection.pst.executeQuery();
            while(MyConnection.rs.next()){
                table.addRow(new String[]{MyConnection.rs.getString(1),MyConnection.rs.getString(2)});
            }
            
            MyConnection.con.close();
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "DEPARTMENTS NOT FOUND SYSTEM ERROR!", "ERROR",JOptionPane.ERROR_MESSAGE);
            
        }
        
    }
    
    public void clear(){
        
        txtDepID.setText(null);
        txtDepName.setText(null);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepAdd;
    private javax.swing.JButton btnDepDelete;
    private javax.swing.JButton btnDepLogout;
    private javax.swing.JButton btnDepRefresh;
    private javax.swing.JButton btnDepSearch;
    private javax.swing.JButton btnDepUpdate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDepName;
    private javax.swing.JLabel lblDepartmentID;
    private javax.swing.JTable tblDepartment;
    private javax.swing.JTextField txtDepID;
    private javax.swing.JTextField txtDepName;
    private javax.swing.JTextField txtDepSearch;
    // End of variables declaration//GEN-END:variables
}
