package interfaces;

import classes.Designation;
import classes.MyConnection;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class DesignationsManage extends javax.swing.JFrame {
    
    private String userName;
    private String userType;

    public DesignationsManage(String userN, String userT) {
        initComponents();
        showAll();
        
        //Save user details
        userName = userN;
        userType = userT;
        
                //Login Image fit to screen
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("3d-casual-life-searching-for-new-employees.png")));
        
        Image img1 = myimage.getImage();
        Image img2 = img1.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        jLabel3.setIcon(i);
        
        //GET DATA TO COMBO BOX
        try {
            
            String sql = "SELECT depID, depName FROM tblDepartment";
            
            MyConnection.getConnection();
            MyConnection.pst = MyConnection.con.prepareStatement(sql);
            MyConnection.rs = MyConnection.pst.executeQuery();
            
            while(MyConnection.rs.next()){
                String id = MyConnection.rs.getString("depID");
                String depName = MyConnection.rs.getString("depName");
                cmbDesDepID.addItem(depName);
            }
            MyConnection.con.close();
            
            
        } catch (Exception e) {
            
            System.out.println("Department Combo box error (constructor method)" + e.getMessage());
        }
        
        addTableSelectionListener();
        
        
    }
    
    public DesignationsManage(){
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDesDepID = new javax.swing.JLabel();
        txtDesID = new javax.swing.JTextField();
        txtDesName = new javax.swing.JTextField();
        lblDesName = new javax.swing.JLabel();
        txtDesSearch = new javax.swing.JTextField();
        btnDesSearch = new javax.swing.JButton();
        btnDesAdd = new javax.swing.JButton();
        btnDesUpdate = new javax.swing.JButton();
        btnDesLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDesignation = new javax.swing.JTable();
        btnDesDelete = new javax.swing.JButton();
        btnDesRefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblDesID = new javax.swing.JLabel();
        cmbDesDepID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDesDepID.setText("DEPARTMENT NAME");
        jPanel1.add(lblDesDepID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));
        jPanel1.add(txtDesID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 320, 32));
        jPanel1.add(txtDesName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 320, 32));

        lblDesName.setText("DESIGNATION NAME");
        jPanel1.add(lblDesName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));
        jPanel1.add(txtDesSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 260, 39));

        btnDesSearch.setText("SEARCH");
        btnDesSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 120, 33));

        btnDesAdd.setText("ADD");
        btnDesAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 99, 33));

        btnDesUpdate.setText("UPDATE");
        btnDesUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 99, 33));

        btnDesLogout.setText("BACK");
        btnDesLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, 110, 33));

        tblDesignation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DESIGNATION ID", "DESIGNATION NAME", "DEPARTMENT ID", "DEPARTMENT NAME"
            }
        ));
        jScrollPane1.setViewportView(tblDesignation);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 320));

        btnDesDelete.setText("DELETE");
        btnDesDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 99, 33));

        btnDesRefresh.setText("REFRESH");
        btnDesRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 99, 33));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 370, 260));

        lblDesID.setText("DESIGNATION ID");
        jPanel1.add(lblDesID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jPanel1.add(cmbDesDepID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesSearchActionPerformed
        Designation search = new Designation();
        search.setDesID(txtDesSearch.getText());
        search.setDesName(txtDesSearch.getText());
        
        if(search.searchDesignation()){
            txtDesID.setText(search.getDesID());
            txtDesName.setText(search.getDesName());
            cmbDesDepID.setSelectedItem(search.departmentSearchByID(search.getDepID()));
            
            DefaultTableModel model = (DefaultTableModel)tblDesignation.getModel();
            model.setRowCount(0);
            
            model.addRow(new String[]{search.getDesID(),search.getDesName(),search.getDepID(),search.departmentSearchByID(search.getDepID())});
            
        }else{
            JOptionPane.showMessageDialog(null, "DESIGNATION NOT FOUND!","NOT FOUND",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDesSearchActionPerformed

    private void btnDesAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesAddActionPerformed
        Designation add= new Designation();
        add.setDesID(txtDesID.getText());
        add.setDesName(txtDesName.getText());
        add.setDepID(add.departmentSearchByName(cmbDesDepID.getSelectedItem().toString()));
        
        if(add.addDesignation()){
            
            JOptionPane.showMessageDialog(null, "DESIGNATION ADDED!", "DESIGNATION ADDED", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            JOptionPane.showMessageDialog(null, "DESIGNATION ADD FAILED!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        clear();
        showAll();
        
        
    }//GEN-LAST:event_btnDesAddActionPerformed

    private void btnDesDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesDeleteActionPerformed
        Designation delete = new Designation();
        delete.setDesID(txtDesID.getText());
        
        if(delete.deleteDesignation()){
            JOptionPane.showMessageDialog(null, "DESIGNATION DELETED!","DELETE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "DESIGNATION NOT DELETED, TRY AGAIN!","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        showAll();
    }//GEN-LAST:event_btnDesDeleteActionPerformed

    private void btnDesRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesRefreshActionPerformed
        showAll();
    }//GEN-LAST:event_btnDesRefreshActionPerformed

    private void btnDesUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesUpdateActionPerformed
        Designation update = new Designation();
        update.setDesID(txtDesID.getText());
        update.setDesName(txtDesName.getText());
        update.setDepID(update.departmentSearchByName(cmbDesDepID.getSelectedItem().toString()));
        
        if(update.updateDesignation()){
            
            JOptionPane.showMessageDialog(null, "DESIGNATION UPDATED!", "DESIGNATION UPDATED", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            
            JOptionPane.showMessageDialog(null, "DESIGNATION UPDATE FAILED!", "ERROR", JOptionPane.ERROR_MESSAGE);
            
        }
        
        showAll();
        clear();
        
    }//GEN-LAST:event_btnDesUpdateActionPerformed

    private void btnDesLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesLogoutActionPerformed
        EmployeeManage manager = new EmployeeManage(userName,userType);
        manager.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDesLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignationsManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignationsManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignationsManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignationsManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignationsManage().setVisible(true);
            }
        });
    }
    
    public void addTableSelectionListener(){
       tblDesignation.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
           @Override
           public void valueChanged(ListSelectionEvent e) {
               if(!e.getValueIsAdjusting()){
                   int selectedRow = tblDesignation.getSelectedRow();
                   
                   if(selectedRow != -1){
                       txtDesID.setText(tblDesignation.getValueAt(selectedRow,0).toString());
                       txtDesName.setText(tblDesignation.getValueAt(selectedRow, 1).toString());
                       cmbDesDepID.setSelectedItem(tblDesignation.getValueAt(selectedRow, 3).toString());
                       
                       
                       
                   }
               }
           }
       });
    }
    
    private void clear(){
        
        txtDesID.setText(null);
        txtDesName.setText(null);
        txtDesSearch.setText(null);
        
    }
    
    private void showAll(){
        
        DefaultTableModel model = (DefaultTableModel)tblDesignation.getModel();
        model.setRowCount(0);
        
        Designation show = new Designation();
        show.viewAll();
        
        try {
            
            MyConnection.rs = MyConnection.pst.executeQuery();
            while(MyConnection.rs.next()){
                model.addRow(new String[]{MyConnection.rs.getString(1),MyConnection.rs.getString(2),MyConnection.rs.getString(3),show.departmentSearchByID(MyConnection.rs.getString(3))});
            }
            
            MyConnection.con.close();
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "DESIGNATIONS NOT FOUND SYSTEM ERROR!" + e.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
            
        }
        
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesAdd;
    private javax.swing.JButton btnDesDelete;
    private javax.swing.JButton btnDesLogout;
    private javax.swing.JButton btnDesRefresh;
    private javax.swing.JButton btnDesSearch;
    private javax.swing.JButton btnDesUpdate;
    private javax.swing.JComboBox<String> cmbDesDepID;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesDepID;
    private javax.swing.JLabel lblDesID;
    private javax.swing.JLabel lblDesName;
    private javax.swing.JTable tblDesignation;
    private javax.swing.JTextField txtDesID;
    private javax.swing.JTextField txtDesName;
    private javax.swing.JTextField txtDesSearch;
    // End of variables declaration//GEN-END:variables
}
